app/mongo_/views.py
from flask import (Blueprint, render_template, request, redirect, flash, jsonify,
                   current_app)
from mongo_.mongo_ import *

mongo_bp = Blueprint('mongo_bp', __name__,
                     template_folder='templates', static_folder='static')


@mongo_bp.errorhandler(404)
def page_not_found(e):
    return "<h1>404</h1><p>The resource could not be found.</p>", 404


@mongo_bp.route('/mongo/')
@mongo_bp.route('/mongo/index.html')
def main():
    output = list(query_mgdb_latest(current_app.config['MGDB_DBNAME']))
    return render_template('mongo_/index.html', output=output, notes="")


@mongo_bp.route('/mongo/filter_proj_id', methods=["GET", "POST"])
def filter_proj_id():
    if request.method == "POST":
        input_proj_id = request.form['filter']
        result, output = filter_mgdb_data_proj_id(
            current_app.config['MGDB_DBNAME'], input_proj_id)
        if result:
            return render_template('mongo_/index.html', output=output, notes="")
        else:
            msg = f'That project id ({input_proj_id}) does not exist in the database'
            print(msg)
            flash(msg, 'warning')
            return render_template('mongo_/index.html', output="")
    return render_template('mongo_/index.html', output="", notes="")


@mongo_bp.route('/mongo/uvplot/<project_id>/<sample_well>')
def uvplot(project_id, sample_well):
    data_dict = get_mongo_data(
        current_app.config['MGDB_DBNAME'], project_id, sample_well)
    plot = create_plot(data_dict)
    return render_template('plot.html', plot=plot, data_dict=data_dict)


@mongo_bp.route('/mongo/job-results/<job_id>', methods=['GET'])
def get_job_results(job_id):
    job = Job.fetch(job_id, connection=conn)

    if job.is_finished:
        res_dict = {'output': f"Job Finished: {job.result}"}
        return jsonify(res_dict), 200
    else:
        res_dict = {'output': f"Job not finished! - id: {job_id}"}
        return jsonify(res_dict), 202


@mongo_bp.route("/mongo/add-task")
def add_task():
    jobs = app.q.jobs  # Get a list of jobs in the queue
    xml_file = get_newest_xmlfile(current_app.config['XML_PARENT_DIR'])
    wl_path = output_file_path()
    with open(wl_path, 'r') as f:
        content = f.readline().split(',')
    tsl_file_path = content[0].strip()
    hostname = content[1].strip()
    print(tsl_file_path)
    print(hostname)
    message = None
    data = format_row_data_to_dict(prepare_row_data(tsl_file_path, xml_file,
                                                    current_app.config['UVDATA_FILE_DIR'], hostname))
    if data:
        # Send a job to the task queue
        sleep_time = app.config['SLEEP_TIME']
        db_name = app.config['MGDB_DBNAME']

        with Connection(redis.from_url(os.getenv('REDIS_URL'))):
            q = Queue()
            task = q.enqueue(upload_mongodb, args=(db_name,
                                                   sleep_time, data),
                             job_timeout=150, result_ttl=1000)
        # task = app.q.enqueue(upload_mongodb, args=('gilson_logs',
        #                                            10, data), job_timeout=15, result_ttl=1000)
        jobs = q.jobs  # Get a list of jobs in the queue
        q_len = len(q)  # Get the queue length
        message = f"Task {task.id} queued at {task.enqueued_at.strftime('%a, %d %b %Y %H:%M:%S')}. {q_len} jobs queued"

    return f"message={message}, jobs={jobs}"

app/mongo_/templates/mongo_/base.html
<!DOCTYPE html>
<html>
<head>
	<title>GILSON LOGS</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<!-- <script src=" {{ url_for('static', filename='css/bootstrap.min.css') }}"></script> -->
	<!-- <script src=" {{ url_for('static', filename='jquery-3.5.1.min.js') }}"></script> -->
	<!-- <script src=" {{ url_for('static', filename='js/bootstrap.min.js') }}"></script> -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
	<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
	<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
	<link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.ico') }}" />

</head>
	<body>

      <div class="panel-heading">
	      <a href="{{ url_for('mongo_bp.main') }}"><h1>Gilson Logs</h1></a>
      </div>


  {% block body %}
  {% endblock %}


  <script type="text/javascript" src="{{url_for('static', filename='app.js') }}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>

   {% block script %}
   {% endblock %}

</body>
</html>

app/mongo_/templates/mongo_/index.html
{% extends 'mongo_/base.html' %}

{% block body %}

<div class="container">

      <div class="row">
      <div class="col-7">
	<form action="/mongo/filter_proj_id" method="POST">
	  <div class="form-group">
	    <div class="custom-file">
	      <input type="text" name="filter" id="filter">
	      <label for="filter">Filter by Project ID</label>
	    </div>
	  </div>
       </div>
      </div>

      <br>
      <div class="row">

      <div class="col-4">
	<button type="submit">Submit</button>
      </div>

      <div class="col-5" id="flash-msg">
      {% with errors = get_flashed_messages(category_filter=["warning"]) %}
	  {% if errors %}
	      {%- for message in errors %}
		<div>
		  <span id="warning-msg"><strong>{{ message }}</strong></span>
		      <button onclick="close_btn()" type="button" class="close" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
		      </button>
		  </div>
	      {% endfor -%}
	  {% endif %}
      {% endwith %}
      </div>

      </div>
      </form>

    </div>

		    <br>

		<div id="output">
			<table class="table table-hover">
			<thead>
				<tr>
					<th>Finish Time</th>
					<th>Project ID</th>
					<th>Gilson Number</th>
					<th>Method Name</th>
					<th>Sample Name</th>
					<th>Barcode</th>
					<th>Brooks Barcode</th>
					<th>Plate Suffix</th>
					<th>Sample Well</th>
					<th>Plate Location</th>
					<th>TSL File</th>
					<th>UVDATA File</th>
					<th>UV Trace</th>
				</tr>
			</thead>
			<tbody>
			{% for ddict in output %}
			{% set cnt = loop.index %}
			<tr>
				{% for key, value in ddict.items() %}
				{% if key|string() == 'project_id' %}
					<td id="project-id-group">
						{{ value }}
					</td>
				{% elif key|string() == 'sample_well' %}
				<td id="sample-well-group-{{ cnt }}">
						{{ value }}
					</td>
				{% else %}
					<td>
						{{ value }}
					</td>
				{% endif %}
				{% endfor %}
					<td>
					<label for="plot-click-{{loop.index}}">
					<img src="{{url_for('static',
						filename='line_graph_icon.png')}}"
					        align="middle" width=50 />
					</label>
					<button id="plot-click-{{loop.index}}"
						     onclick="popup_center(this,
						     'mongo', 1000, 600)" class="visuallyhidden">
					</button>
					</td>
			{% endfor %}

			</tr>
			</tbody>
			</table>
		</div>
	</div>

	<br>

	<div> <span id="note-div"> {{ notes }} </span></div>

{% endblock %}