app/elasticsearch_/views.py
from flask import (Blueprint, render_template, request,
                   flash, jsonify, current_app, redirect)
from elasticsearch_.elasticsearch_ import *
from worker import Connection, redis, Queue
from mongo_.mongo_ import *


elasticsearch_bp = Blueprint(
    'elasticsearch_bp', __name__, template_folder='templates', static_folder='static')


@elasticsearch_bp.errorhandler(404)
def page_not_found(e):
    return "<h1>404</h1><p>The resource could not be found.</p>", 404


@elasticsearch_bp.route('/')
def blank_main():
    return render_template('elasticsearch_/index.html', output="",
                           switch_var='log')


@elasticsearch_bp.route('/es/')
def main():
    host = current_app.config['HOSTNAME']
    # query on server-side
    output = ""
    output = query_ES_latest(host, current_app.config['ES_INDEX_NAME'], 8)
    if output:
        output = sort_colnames_ES(output)

    # if it exists, assigned from app.py init, then use that for plot rendering;
    # query for client-side
    if current_app.config['HOST_PLOT']:
        host = current_app.config['HOST_PLOT']

    return render_template('elasticsearch_/index.html', output=output,
                           host=host, switch_var='log')


@elasticsearch_bp.route('/es/show-current-data/<hostname>')
def show_current_data(hostname):
    # tsl_file_path = get_filepath_mgdb(hostname)
    # returns None if cannot find in mgdb
    current_row_data = get_latest_rowdata_mgdb(hostname)

    if current_row_data:
        tsl_file_path = current_row_data['TSL_FILEPATH']
        try:
            current_ts = datetime.strptime(
                current_row_data['FINISH_DATE'], "%m/%d/%Y %I:%M:%S %p")
        except ValueError as e:
            current_ts = datetime.strptime(
                current_row_data['FINISH_DATE'], "%Y-%b-%d %H:%M:%S")

        data = prepare_row_data_ES(tsl_file_path, current_row_data['SAMPLE_WELL'],
                                   current_row_data['PLATE_POSITION'],
                                   current_row_data['SEQ_NUM'],
                                   current_ts,
                                   current_app.config['UVDATA_FILE_DIR'], hostname)

        data = sort_dictkeys(data)
        # for k, v in data.items():
        #     print(k, v)

        return jsonify(data), 202

    return jsonify({'output': f'No data retrieved for {hostname}'})

# @elasticsearch_bp.route('/es/post/filepath/', methods=['POST'])
# def post_filepath_mongodb():
#     # force mimetype to be application/json
#     input_json = None
#     input_json = request.get_json(force=True)
#     if input_json:
#         print(f'data from client-side: {input_json}')
#         check = check_gilson_nbr(
#             app.config['MGDB_FP'], input_json["gilson_number"])
#         if not check:
#             # insert into tsl file path database
#             insert_mgdb(current_app.config['MGDB_FP'], input_json)
#             print(f'inserted new tsl file path - {input_json}')
#         else:
#             update_mgdb(current_app.config['MGDB_FP'], input_json)
#             print(f'updated new tsl file path - {input_json}')
#         return jsonify({'status': f'submitted to mongodb', input_json)


@elasticsearch_bp.route('/es/post/rowdata', methods=['POST'])
def post_rowdata_mongodb():
    '''includes both filepath and the xml row data (combined into one post
    request)'''
    input_json = None
    # force mimetype to be application/json
    input_json = request.get_json(force=True)
    print(f'data from client-side: {input_json}')

    if input_json:
        # must remove empty fields that are requisite for NPSG endpoint
        # (gateway so that vlans can communicate to linux VM); dont upload empty
        # values into mgongodb
        for empty_keys in ["PROJECT_ID", "SAMPLE_NAME", "BARCODE",
                           "PLATE_ID", "BROOKS_BARCODE"]:
            try:
                input_json.pop(empty_keys)
            except KeyError:
                pass

        # insert row data (XML & filepath) to database
        insert_mgdb(current_app.config['MGDB_ROWDATA'], input_json)
        print(f'inserted new data row - {input_json}')
        # must remove '_id' key since it is not json serialisable
        input_json.pop('_id')

        print(
            f'current tsl file (from post view): {input_json["TSL_FILEPATH"]}')

        # data = prepare_row_data_ES(input_json['TSL_FILEPATH'], input_json['SAMPLE_WELL'],
        #                            input_json['PLATE_POSITION'],
        #                            input_json['SEQ_NUM'],
        #                            current_ts,
        #                            current_app.config['UVDATA_FILE_DIR'],
        #                            input_json['GILSON_NUMBER'])

        # add uvdata file dir & tsl file dir for the prepare_row_data_ES() function
        input_json['UVDATA_FILE_DIR'] = current_app.config['UVDATA_FILE_DIR']
        input_json['APP_TSL_FILEPATH'] = app.config['TSL_FILEPATH']

        # Send a job to the task queue
        # result_ttl - specifies how long (in seconds) successful jobs and their results are kept
        index_name = current_app.config['ES_INDEX_NAME']
        sleep_time = current_app.config['SLEEP_TIME']
        host = current_app.config['HOSTNAME']
        redis_url = current_app.config['REDIS_URL'].strip().replace('"', '')
        print(f'redis url from add-task endpoint: {redis_url}')

        oracle_params = {
            'ORACLE_USER': app.config['ORACLE_USER'],
            'ORACLE_PASS': app.config['ORACLE_PASS'],
            'ORACLE_HOST': app.config['ORACLE_HOST'],
            'ORACLE_PORT': app.config['ORACLE_PORT'],
            'ORACLE_SERVNAME': app.config['ORACLE_SERVNAME'],
            'ORACLE_TABLENAME': app.config['ORACLE_TABLENAME']
        }

        with Connection(redis.from_url(redis_url)):
            q = Queue()
            task = q.enqueue(upload_data_to_ES, args=(host,
                                                      index_name,
                                                      sleep_time,
                                                      input_json,
                                                      oracle_params),
                             job_timeout=60*5, result_ttl=1000)

        # remove the APP_TSL_FILEPATH and UVDATA_FILE_DIR from input_json (since
        # was used to pass to prepare_row_data_ES() and upload_data_to_ES() only
        # (not needed for the server response)
        input_json = {k: input_json[k] for k in input_json.keys(
        ) - {'UVDATA_FILE_DIR', 'APP_TSL_FILEPATH'}}

        q_len = len(q)  # Get the queue length
        enq_time = task.enqueued_at.strftime('%a, %d-%b-%Y %H:%M: %S')
        message = f"""Task {task.id} queued at {enq_time}; len: {q_len} jobs queued; updated row data in oracle database"""
        return jsonify({'output': message, 'submitted-data': input_json}), 202
    return jsonify({'status': f'error, no input JSON data'})


@ elasticsearch_bp.route('/es/get/rowdata/<gilson_number>', methods=['GET'])
def get_rowdata_mongodb(gilson_number):
    rowdata = get_latest_rowdata_mgdb(gilson_number)
    if rowdata:
        print(f'retrieved data row - {rowdata}')
        return jsonify({"output": rowdata})
    print(f'No data retrieved for most recent run from {gilson_number}')
    return jsonify({"output": "No data"})


# @ elasticsearch_bp.route('/es/get/tslfilepath/<gilson_number>', methods=['GET'])
# def get_tslfilepath_mongodb(gilson_number):
#     tsl_filepath = get_filepath_mgdb(gilson_number)
#     if tsl_filepath:
#         print(f'retrieved tsl file path- {tsl_filepath}')
#         return jsonify({"output": tsl_filepath})
#     print(f'No filepath retrieved for {gilson_number}')
#     return jsonify({"output": "No tsl filepath"})


@ elasticsearch_bp.route('/es/uvplot/<project_id>/<sample_well>')
def uvplot(project_id, sample_well):
    data_dict = query_ES_data(current_app.config['HOSTNAME'],
                              current_app.config['ES_INDEX_NAME'], project_id, sample_well)
    # print(f"brooks bc: {data_dict['brooks_bc']}")
    for k in data_dict.keys():
        print(k)
    plot = create_plot(data_dict)
    return render_template('elasticsearch_/plot.html', plot=plot, data_dict=data_dict)


@ elasticsearch_bp.route('/es/filter_proj_id', methods=["POST"])
def filter_proj_id():
    if request.method == "POST":
        result = None
        host = current_app.config['HOSTNAME']
        input_proj_id = request.form['filter']
        result, output = check_ES_proj_id(
            host, current_app.config['ES_INDEX_NAME'], input_proj_id)

        if not input_proj_id:
            # handle when not input; but click submit button
            msg = 'No project ID entered'
            print(msg)
            flash(msg, 'warning')
            return redirect('/')
        if result:
            print(output)
            output = sort_colnames_ES(output)
            if current_app.config['HOST_PLOT']:
                host = current_app.config['HOST_PLOT']
            return render_template('elasticsearch_/index.html', output=output,
                                   host=host, switch_var='log')
        else:
            msg = 'That project id does not exist'
            print(msg)
            flash(msg, 'warning')
            return redirect('/')

    return redirect('/')


@ elasticsearch_bp.route('/es/task-results/<task_id>', methods=['GET'])
def get_task_results(task_id):
    task = None
    redis_url = current_app.config['REDIS_URL'].strip().replace('"', '')
    with Connection(redis.from_url(redis_url)):
        q = Queue()
        task = q.fetch_job(task_id)
    if task:
        res_dict = {"data": {
            "task_id": task.get_id(),
            "task_function": task.func_name,
            "task_exc_info": task.exc_info,
            "task_enqueue_time": task.enqueued_at,
            "task_start_time": task.started_at,

app/elasticsearch_/templates/elasticsearch_/base.html
<!DOCTYPE html>
<html>
<head>
	<title>GILSON LOGS</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<!-- <script src=" {{ url_for('static', filename='css/bootstrap.min.css') }}"></script> -->
	<!-- <script src=" {{ url_for('static', filename='jquery-3.5.1.min.js') }}"></script> -->
	<!-- <script src=" {{ url_for('static', filename='js/bootstrap.min.js') }}"></script> -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
	<link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.ico') }}" />

</head>
	<body>

      <div class="panel-heading">
	      <!-- <a href="{{ url_for('elasticsearch_bp.main') }}"><h1>Gilson Logs</h1></a> -->
		<h1>Gilson Logs</h1>
      </div>
    	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<ul class="nav nav-tabs">
	  <li class="nav-item">
	    <!-- <a class="nav-link active" href="#" id="log-navbar" onclick="switch_tabs(this, '/es/logs');">Logs</a> -->
	    {% if switch_var == 'log' %}
		    {% set log_tab = 'nav-link active' %}
		    {% set wl_tab = 'nav-link' %}
	   {% else %}
	   	{% set log_tab = 'nav-link' %}
		{% set wl_tab = 'nav-link active' %}
	{% endif %}
		<a class="{{ log_tab }}" href="{{ url_for('elasticsearch_bp.main') }}" onclick="switch_tabs(this)" id="log-navbar">Logs</a>
	  </li>
	  <li class="nav-item">
	    <!-- <a class="nav-link" href="#" id="wl-navbar" onclick="switch_tabs(this, '/es/form-combine-worklists');">Combine Worklists</a> -->
	    <a class="{{ wl_tab }}" href="{{ url_for('elasticsearch_bp.form_combine_worklists') }}" onclick="switch_tabs(this)" id="wl-navbar">Combine Worklists</a>
	  </li>
	</ul>
	</nav>

  {% block body %}
  {% endblock %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
  <script type="text/javascript" src="{{url_for('static', filename='app.js') }}"></script>

   {% block script %}
   {% endblock %}

</body>
</html>

app/elasticsearch_/templates/elasticsearch_/combine_worklists.html
{% extends 'elasticsearch_/base.html' %}
{% block body %}
<div>
	<img src="{{url_for('static',
	filename='tube_rack.svg')}}"
	align="middle" width=200/ id="tube-rack">
</div>
<br>
<div class="blank-container">
      <div class="row">
		<div class="col-12">
			<form action='/es/combine-worklists' method='post'
			id="cmb-wl-form" class="form-inline">
				  <label for="rack1">Rack1 Code: </label>
				  <input type="text" id="rack1" name="rack1"
				  data-toggle="tooltip" title="Use a barcode scanner or manually type in the rack barcode/ID; starting with '15' to combine TSL worklists" class="tooltip-cls">
				  <label for="rack2">Rack2 Code: </label>
				  <input type="text" id="rack2" name="rack2" data-toggle="tooltip" title="Use a barcode scanner or manually type in the rack barcode/ID; starting with '15' to combine TSL worklists" class="tooltip-cls">
				  <input type="submit" value="Submit" id="combine-wrklst-btn">
				  <!-- onclick="inject_tsl_view()"> -->
			</form>
		</div>

		<br>
		<div id="tsl-panel">
			{% include 'elasticsearch_/flash_message.html' %}
			<br>
			{% include 'elasticsearch_/tsl_view.html' %}
		</div>
      </div>
</div>
{% endblock %}

app/elasticsearch_/templates/elasticsearch_/flash_message.html
<br>
<div class="col-8" id="flash-msg">
{% with errors = get_flashed_messages(with_categories=true) %}
  {% if errors %}
      {%- for category, message in errors %}
	<div>
	      <div class="alert alert-{{category}}" role="alert">{{message }}
	      <button onclick="close_btn(this)" type="button" class="close" aria-label="Close">
		      <span aria-hidden="true">&times;</span>
	      </button>
	      </div>
	  </div>
      {% endfor -%}
  {% endif %}
{% endwith %}
</div>

app/elasticsearch_/templates/elasticsearch_/form.html
<br>
<div class="row" id="input-form">
<div class="col-10">
<form action="/es/filter_proj_id" method="POST" class="form-inline">
      <label for="filter">Filter by Project ID: </label>
      <input type="text" name="filter" id="filter" data-toggle="tooltip" title="Use a barcode scanner or manually enter a project ID to filter the list" class="tooltip-cls">
      <input type="submit" value="Submit" id="submit-btn">
</div>
</div>
</form>

{% include 'elasticsearch_/flash_message.html' %}
</div>

app/elasticsearch_/templates/elasticsearch_/index.html
{% extends 'elasticsearch_/base.html' %}

{% block body %}

{% if switch_var == 'log' %}
	{% include 'elasticsearch_/form.html' %}
{% endif %}

{% include 'elasticsearch_/logs.html' %}

{% endblock %}

app/elasticsearch_/templates/elasticsearch_/logs.html
<br>
<div id="output">
	<table>
	<thead>
		<tr>
			<th class="tbl-hdr-logs">FINISH TIME</th>
			<th class="tbl-hdr-logs">SEQ NUM</th>
			<th class="tbl-hdr-logs">PROJECT ID</th>
			<th class="tbl-hdr-logs">METHOD NAME</th>
			<th class="tbl-hdr-logs">SAMPLE NAME</th>
			<th class="tbl-hdr-logs">BARCODE</th>
			<th class="tbl-hdr-logs">PLATE SUFFIX</th>
			<th class="tbl-hdr-logs">BROOKS BARCODE</th>
			<th class="tbl-hdr-logs">SAMPLE WELL</th>
			<th class="tbl-hdr-logs">PLATE LOCATION</th>
			<th class="tbl-hdr-logs">GILSON NUMBER</th>
			<th class="tbl-hdr-logs">TSL FILE</th>
			<th class="tbl-hdr-logs">UVDATA FILE</th>
			<th class="tbl-hdr-logs">UV TRACE</th>
		</tr>
	</thead>
	{% for ddict in output %}
	{% set cnt = loop.index %}
	<tr class="tbl-grp-colour-logs">
		{% for key, value in ddict.items() %}
		{% if key|string() == 'PROJECT_ID' %}
			<td id="project-id-group-{{ cnt }}">
				{{ value }}
			</td>
		{% elif key|string() == 'SAMPLE_WELL' %}
			<td id="sample-well-group-{{ cnt }}">
				{{ value }}
			</td>
		{% else %}
			<td>
				{{ value }}
			</td>
		{% endif %}
		{% endfor %}
			<td>
			<label for="plot-click-{{loop.index}}">
				<img src="{{url_for('static',
					filename='line_graph_icon.png')}}"
					align="middle" width=50 />
			</label>
			<button id="plot-click-{{loop.index}}"
				     onclick="popup_center(this, '{{host}}', 'es', 1000, 600)" class="visuallyhidden">
			</button>
			</td>
	{% endfor %}

	</tr>
	</table>
</div>

app/elasticsearch_/templates/elasticsearch_/plot.html
{% extends 'base_plot.html' %}

{% block body %}

<div class="row">
	<div class="col-md-6">
	<h4>
		<li>Project ID:
			<span class="data-info-colour">
				{{data_dict.PROJECT_ID|safe}}/{{data_dict.PLATE_ID|safe}}
			</span>
		</li>
		<li>Method Name:
			<span class="data-info-colour">
				{{data_dict.METHOD_NAME|safe}}
			</span>
		</li>
		<li>Sample Name:
			<span class="data-info-colour">
				{{data_dict.SAMPLE_NAME|safe}}
			</span>
		</li>
		<li>Sample Well:
			<span class="data-info-colour">
				{{data_dict.SAMPLE_WELL|safe}}
			</span>
		</li>
		<li>Plate Location:
			<span class="data-info-colour">
				{{data_dict.PLATE_POSITION|safe}}
			</span>
		</li>
		<li>Barcode:
			<span class="data-info-colour">
				{{data_dict.BARCODE|safe}}
			</span>
		</li>
		<li>Brooks Barcode:
			<span class="data-info-colour">
				{{data_dict.BROOKS_BARCODE|safe}}
			</span>
		</li>
		<li>Gilson Number:
			<span class="data-info-colour">
				{{data_dict.GILSON_NUMBER|safe}}
			</span>
		</li>
	</h4>
		    <div class="chart" id="plot">
			<script>
				var config = {
					displayLogo:false
				};
				var graphs = {{plot | safe}};
				Plotly.plot('plot',graphs,config=config);
				// remove stupid plotly logo since setting in config param didn't work
				var list = document.getElementsByClassName('modebar modebar--hover ease-bg');
				list[0].removeChild(list[0].childNodes[3]);
				console.log('removed first modebar button');
				list[0].removeChild(list[0].childNodes[3]);
		        </script>
		    </div>
	</div>
</div>

{% endblock %}

app/elasticsearch_/templates/elasticsearch_/tsl_view.html
<h2>{{ title }}</h2>
  <div>
	<table>
	    <thead>
	    <tr>
		{% for col in columns %}
			<th class="tbl-hdr-colour">{{col}}</th>
		{% endfor %}
	    </tr>
	    </thead>
	    {% for row in row_data %}
	    {% set outer_loop = loop.index0 %}
		{% if cls_name[outer_loop][:3] == 'tbl' %}
		    <tr class="{{ cls_name[outer_loop] }}">
		{% endif %}
		{% for r in row %}
			<td>{{r}}</td>
		{% endfor %}
		    </tr>
	    {% endfor %}

	</table>
  </div>